# Generated by Django 3.2.25 on 2026-03-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecg', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('predicted_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='ecg.ecgrecord')),
            ],
        ),
    ]
